# Generated by Django 5.1.4 on 2024-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("brigade_number", models.IntegerField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
                ("specialization", models.CharField(max_length=50)),
            ],
        ),
    ]
